name: Python Linting
 on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on
 jobs:
  lint:
    runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v2
       - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change this to your desired Python version
       - name: Install dependencies
        run: pip install --upgrade autopep8
       - name: Lint Python code
        run: autopep8 --in-place --recursive .
       - name: Commit changes
        run: |
          git config --global user.name "Navid-JL"
          git config --global user.email "navidjalili3@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Autopep8 linting"